"""add severity column to reports

Revision ID: bcf841a6677a
Revises: 9b75a99b038c
Create Date: 2025-07-19 02:30:56.719711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf841a6677a'
down_revision: Union[str, Sequence[str], None] = '9b75a99b038c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('severity', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'severity')
    # ### end Alembic commands ###
