name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build-scan:
    name: Test, Build & Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          export PYTHONPATH="${{ github.workspace }}"
          pytest tests/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image with SHA tag
        run: |
          docker build -f docker/Dockerfile -t incidentvault:${{ github.sha }} .

      - name: Install Trivy and scan the image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: incidentvault:${{ github.sha }}
          format: table
          exit-code: 0  
